#!/bin/sh
#Sub script to emit the filename of any failed decodes or non-standard files
#Hugh O'Brien 2014, obrien.hugh@gmail.com
flac --test --totally-silent --warnings-as-errors "$1" || echo "Decode Error: $1"

sample_rate=$(flac --analyze --silent --stdout "$1" | head --lines=1 | cut --fields=5)
[ "$sample_rate" != "sample_rate=44100" ] && echo "Non 44.1kHz file: $1"
